version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
    env_file:
      - ./docker/rest/.env
    ports:
      - "80:80"
  postgres:
    build: ./docker/postgres/
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
#    volumes:
#      - db:/var/lib/postgresql/data
volumes:
  db:
